CREATE TABLE jobs(
    job_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    job_title VARCHAR(255),
    min_salary DECIMAL(10),
    max_salary DECIMAL(10),
    PRIMARY KEY(job_id)
);
CREATE TABLE regions(
    region_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    region_name VARCHAR(255),
    PRIMARY KEY(region_id)
);
CREATE TABLE countries(
    country_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    country_name VARCHAR(255),
    region_id NUMBER REFERENCES regions(region_id),
    PRIMARY KEY(country_id)
);
CREATE TABLE locations(
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    street_address VARCHAR(255),
    postal_code VARCHAR(6),
    emacityil VARCHAR(255),
    state_province VARCHAR(12),
    country_id NUMBER REFERENCES countries(country_id),
    PRIMARY KEY(location_id)
);

CREATE TABLE job_history(
    start_date DATE,
    end_date DATE,
    max_salary DECIMAL(10)
);
CREATE TABLE departments(
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR(255),
    PRIMARY KEY(department_id)
);
CREATE TABLE employees(
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    phone_number VARCHAR(12),
    hire_date DATE,
    salary DECIMAL(10),
    commision_pct VARCHAR(255),
    PRIMARY KEY(employee_id)
);

ALTER TABLE employees
    ADD manager_id NUMBER REFERENCES employees(employee_id)
    ADD job_id NUMBER REFERENCES jobs(job_id)
    ADD department_id NUMBER REFERENCES departments(department_id);


ALTER TABLE departments
    ADD manager_id NUMBER REFERENCES employees(employee_id)
    ADD location_id NUMBER REFERENCES locations(location_id);


ALTER TABLE job_history
    ADD employee_id NUMBER REFERENCES employees(employee_id)
    ADD department_id NUMBER REFERENCES departments(department_id)
    ADD job_id NUMBER REFERENCES jobs(job_id);
