-- ZADANIE 1

SELECT LAST_NAME, SALARY AS "WYNAGRODZENIE"
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50 AND SALARY >= 2000 AND SALARY <= 7000
ORDER BY LAST_NAME;

--

-- ZADANIE 2

-- ACCEPT user_column PROMPT 'Podaj nazwę kolumny' -- Do SQL Developer

SELECT HIRE_DATE, LAST_NAME, EMAIL
FROM EMPLOYEES
WHERE MANAGER_ID iS NOT NULL AND TO_CHAR(HIRE_DATE, 'YYYY') = 2005
ORDER BY HIRE_DATE;

